.github/workflows/ci.yml
enabler/jest.config.ts
enabler/package-lock.json
enabler/package.json
enabler/src/style/button.module.scss

- Add jest and `npm run test` command.
- Remove duplicated properties in CSS in enabler module

Improve enabler module

---

.github/workflows/ci.yml
enabler/package-lock.json
enabler/package.json
enabler/test/sample.spec.ts
processor/test/sample.spec.ts

Since test cases are required in connect certification, test cases template are added for publishing this template in comercetools connect. Actual test cases would be implemented in next step

chore(template): add dummy test cases for both modules

---

enabler/src/payment-enabler/payment-enabler-mock.ts

Remove `private` access modifier from `MockPaymentEnabler` constructor

fix(enabler): change the access modifier of MockPaymentEnabler constructor

---

processor/src/services/abstract-payment.service.ts
processor/src/services/mock-payment.service.ts

Add typescript doc based on the standardization defined by [TSDoc](https://tsdoc.org)

feat(processor) - add typescript doc

---

processor/test/mock-payment.service.spec.ts
processor/test/utils/mock-payment-data.ts

chore(template): clean up and tiny fixes

---

processor/test/mock-payment.service.spec.ts

write unit test case for getStatus function in  `MockPaymentService`

Add getStatus unit test

---

.github/workflows/ci.yml
enabler/src/components/payment-methods/card/card.ts

- Add typescript compilation into CI pipeline for both `enabler` and `processor`
- Fix compilation error in `enabler` module

fix(all) - add typescript compilation in pipeline

---

README.md
connect.yaml

- Change `applicationType` to be `assets` for enabler, which supports CDN to static resources
- Update README.md

feat(enabler): change application type for enabler

---

enabler/package.json
enabler/serve.json

Allowing custom domains for CORS and support in connect

CORS support

---

processor/package-lock.json
processor/package.json
processor/src/services/abstract-payment.service.ts
processor/src/services/mock-payment.service.ts
processor/src/services/types/operation.type.ts
processor/test/utils/mock-cart-data.ts
processor/test/utils/mock-payment-results.ts

- Remove platform SDK dependencies
- Rely on connect-payment-sdk for CoCo persistence

fix(processor): remove commercetools platform SDK from dependencies

---

enabler/README.md
enabler/dev-utils/session.js
enabler/index.html
enabler/src/components/payment-methods/invoice/invoice.ts
enabler/src/payment-enabler/payment-enabler-mock.ts
enabler/src/payment-enabler/payment-enabler.ts
processor/src/dtos/mock-payment.dto.ts
processor/src/libs/fastify/context/context.ts
processor/src/server/server.ts
processor/src/services/mock-payment.service.ts
processor/test/mock-payment.service.spec.ts

- Add Invoice payment option in the mock connector.
TODO: (will be done as part of another PR as part of this ticket https://commercetools.atlassian.net/jira/software/c/projects/IM/boards/484?selectedIssue=IM-933)
- Move the Payment Authoziation logic to enabler
- Update documentation

Invoice connector implementation

---

processor/src/services/abstract-payment.service.ts
processor/src/services/mock-payment.service.ts
processor/test/mock-payment.service.spec.ts

- fix the incorrect transaction state. It is set as `failure` when it is expected to be `pending`

fix(processor): fix transaction state conversion

---

processor/package-lock.json
processor/package.json
processor/src/services/abstract-payment.service.ts
processor/test/mock-payment.service.spec.ts

https://commercetools.atlassian.net/browse/SCC-2273

feat(payments): removed validations for payments modifications

---

enabler/src/components/base.ts
enabler/src/components/payment-methods/card/card.ts
enabler/src/payment-enabler/payment-enabler.ts

Follow up of https://github.com/commercetools/connect-payment-integration-adyen/pull/132
See https://commercetools.atlassian.net/browse/SCC-2362

fix(template): align implementation isAvailable

---

.github/workflows/ci.yml
.github/workflows/latest.yml
.github/workflows/publish.yml

@leungkinghin-ct @prateek-ct I have no access to the repository setting and I would like to setup the following repository variables:
* CKO_CLIENT_ID
* CKO_CLIENT_SECRET
* CKO_CONNECTOR_KEY

ci(latest): autoupdate checkout connector

---

enabler/src/payment-enabler/payment-enabler.ts
processor/src/dtos/operations/config.dto.ts
processor/src/dtos/operations/payment-componets.dto.ts
processor/src/dtos/operations/payment-intents.dto.ts
processor/src/dtos/operations/status.dto.ts
processor/src/services/mock-payment.service.ts
processor/test/mock-payment.service.spec.ts

* Updating payment methods support in the template
* Adding jsdoc
* Status check to support `message` field

chore(checkout): improve checkout compatibility

---

.github/workflows/bump.yaml
enabler/package-lock.json
enabler/package.json
processor/package-lock.json
processor/package.json

Objective of this workflow will be bumping the version of the connector (enabler and processor) and creating a PR for it.
The result of this workflow is to create a PR like the following: https://github.com/commercetools/connect-payment-integration-template/pull/366

ci: workflow 

---

enabler/package-lock.json
enabler/package.json

chore: update esbuild overwrite

chore: update esbuild overwrite

---

processor/package-lock.json
processor/package.json
processor/src/dtos/operations/transaction.dto.ts
processor/src/libs/fastify/context/context.ts

added a method to retrieve the future order number from the session so it could be sent to the payment providers if needed
https://commercetools.atlassian.net/browse/SCC-2635

feat(payments): added support to retrieve the future order number from the session

---

processor/src/dtos/operations/payment-intents.dto.ts
processor/src/services/abstract-payment.service.ts
processor/src/services/types/operation.type.ts

https://commercetools.atlassian.net/browse/SCC-2774
Accept a merchant reference in the payload of the payment intents API.

feat(payments): accept a merchant reference in payment intents API

---

enabler/src/components/payment-methods/card/card.ts

https://commercetools.atlassian.net/browse/SCC-3020 
Small fix as part of an accessibility epic. Added tab indexing for all sample card alerts.

fix(payments): Added tab indexing in sample card for accessibility

---

README.md
enabler/src/components/payment-methods/custom-test-method/custom-test-method.ts
enabler/src/payment-enabler/payment-enabler-mock.ts
enabler/src/payment-enabler/payment-enabler.ts
processor/src/dtos/mock-payment.dto.ts
processor/src/services/mock-payment.service.ts
processor/test/mock-payment.service.spec.ts

Added a new custom test method for testing purposes

feat(enabler): New custom payment method

---

enabler/jest.config.ts

- fix the unit test configuration for enabler

test(enabler): fix the unit test config
